---

- hosts: all
  connection: local
  vars:
    snapshot_name
  tasks:

  - name: Get VM Status
    vmware_guest_facts:
      datacenter: "{{ datacenter_name }}"
      name: "{{ inventory_hostname }}"
    delegate_to: localhost
    register: vm_status
          
  - name: Shutdown VM using VMTools
    vmware_guest_powerstate:
      name: "{{ inventory_hostname }}"
      state: shutdown-guest
      state_change_timeout: 200
    when: vm_status.instance.hw_power_status != 'poweredOff'

  - name: Fallback - wait until power is off
    vmware_guest_facts:
      datacenter: "{{ datacenter_name }}"
      name: "{{ inventory_hostname }}"
    delegate_to: localhost
    register: am_i_off_yet
    until: am_i_off_yet.instance.hw_power_status == 'poweredOff'
    retries: 5
    delay: 60

  - name: Create a snapshot
    vmware_guest_snapshot:
      datacenter: "{{ datacenter_name }}"
      folder: "/{{ datacenter_name }}/vm/"
      name: "{{ inventory_hostname }}"
      state: present
      snapshot_name: {{snapshot_name}}
      description: {{ inventory_hostname }}
    delegate_to: localhost

  - name: Power VM back on
    vmware_guest_powerstate:
      name: "{{ inventory_hostname }}"
      state: powered-on
